# Table of Contents
 <p><div class="lev1 toc-item"><a href="#Vectorization" data-toc-modified-id="Vectorization-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Vectorization</a></div><div class="lev1 toc-item"><a href="#Vectorizing-Logistic-Regression" data-toc-modified-id="Vectorizing-Logistic-Regression-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Vectorizing Logistic Regression</a></div><div class="lev1 toc-item"><a href="#Vectorizing-Logistic-Regression's-Gradient-Output" data-toc-modified-id="Vectorizing-Logistic-Regression's-Gradient-Output-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Vectorizing Logistic Regression's Gradient Output</a></div><div class="lev1 toc-item"><a href="#A-note-on-python/numpy-vectors" data-toc-modified-id="A-note-on-python/numpy-vectors-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>A note on python/numpy vectors</a></div>

# Vectorization
![](https://i.imgur.com/yz60bns.png)

In [1]:
import numpy as np

In [2]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)


In [3]:
%time c = np.dot(a, b)

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 1.49 ms


In [9]:
def loop():
    c = 0
    for i in range(1000000):
        c += a[i] * b[i]

In [10]:
%time loop()

CPU times: user 436 ms, sys: 0 ns, total: 436 ms
Wall time: 437 ms


![](https://i.imgur.com/p94lp3F.png)

![](https://i.imgur.com/62FCVzX.png)

![](https://i.imgur.com/lQnsLDn.png)

# Vectorizing Logistic Regression


![](https://i.imgur.com/3NO1maQ.png)

# Vectorizing Logistic Regression's Gradient Output

![](https://i.imgur.com/5HLkUab.png)

# A note on python/numpy vectors

In [11]:
a = np.random.randn(5)
a

array([-1.50768332, -0.34762576,  0.82402015, -0.15021025,  0.18177096])

In [12]:
a.shape

(5,)

In [13]:
a.T

array([-1.50768332, -0.34762576,  0.82402015, -0.15021025,  0.18177096])

In [14]:
np.dot(a, a.T)

3.1285656758666973

In [15]:
a = np.random.randn(5, 1)
a

array([[-1.45409815],
       [ 0.05631095],
       [ 0.37161622],
       [ 1.92252813],
       [-0.67568557]])

In [16]:
a.shape

(5, 1)

In [17]:
a.T

array([[-1.45409815,  0.05631095,  0.37161622,  1.92252813, -0.67568557]])

In [18]:
np.dot(a, a.T)

array([[  2.11440143e+00,  -8.18816499e-02,  -5.40366459e-01,
         -2.79554460e+00,   9.82513134e-01],
       [ -8.18816499e-02,   3.17092321e-03,   2.09260628e-02,
          1.08259388e-01,  -3.80484969e-02],
       [ -5.40366459e-01,   2.09260628e-02,   1.38098615e-01,
          7.14442637e-01,  -2.51095716e-01],
       [ -2.79554460e+00,   1.08259388e-01,   7.14442637e-01,
          3.69611442e+00,  -1.29902451e+00],
       [  9.82513134e-01,  -3.80484969e-02,  -2.51095716e-01,
         -1.29902451e+00,   4.56550985e-01]])

![](https://i.imgur.com/RWHkYsw.png)